[package]
name = "attestation-service"
version = "0.1.0"
edition = "2021"

[features]
default = [ "rvps-grpc", "rvps-builtin", "all-verifier" ]
all-verifier = [ "verifier/all-verifier" ]
tdx-verifier = [ "verifier/tdx-verifier" ]
sgx-verifier = [ "verifier/sgx-verifier" ]
az-snp-vtpm-verifier = [ "verifier/az-snp-vtpm-verifier" ]
snp-verifier = [ "verifier/snp-verifier" ]
csv-verifier = [ "verifier/csv-verifier" ]
cca-verifier = [ "verifier/cca-verifier" ]

# Only for testing and CI
rvps-builtin = [ "reference-value-provider-service" ]

rvps-grpc = [ "prost", "tonic" ]

# For building gRPC CoCo-AS binary
grpc-bin = [ "clap", "env_logger", "prost", "tonic" ]

# For restful CoCo-AS binary
restful-bin = [ "actix-web", "clap", "env_logger", "thiserror" ]

[[bin]]
name = "as-grpc"
required-features = [ "grpc-bin" ]

[[bin]]
name = "as-restful"
required-features = [ "restful-bin" ]

[dependencies]
actix-web = { workspace = true, optional = true }
anyhow.workspace = true
async-trait.workspace = true
base64 = "0.21"
cfg-if = "1.0.0"
clap = { workspace = true, optional = true }
env_logger = { workspace = true, optional = true }
futures = "0.3.17"
jsonwebtoken = "8"
jwt = { version = "0.16.0", features = ["openssl"]}
# TODO: change it to "0.5", once released.
kbs-types = { git = "https://github.com/virtee/kbs-types", rev = "c90df0e" }
lazy_static = "1.4.0"
log.workspace = true
openssl = "0.10.55"
path-clean = "1.0.1"
prost = { workspace = true, optional = true }
rand = "0.8.5"
rsa = { version = "0.9.2", features = ["sha2"] }
reference-value-provider-service = { path = "../rvps", optional = true }
scroll = { version = "0.11.0", default-features = false, features = ["derive"], optional = true }
serde.workspace = true
serde_json.workspace = true
serde_variant = "0.1.2"
sha2.workspace = true
shadow-rs.workspace = true
strum.workspace = true
time = { version = "0.3.23", features = ["std"] }
thiserror = { workspace = true, optional = true }
tokio.workspace = true
tonic = { workspace = true, optional = true }
uuid = { version = "1.1.2", features = ["v4"] }
verifier = { path = "../verifier", default-features = false }

[build-dependencies]
shadow-rs.workspace = true
tonic-build.workspace = true

[dev-dependencies]
assert-json-diff.workspace = true
rstest.workspace = true
serial_test.workspace = true
sha2.workspace = true
testing_logger = "0.1.1"
walkdir = "2.3.2"
